# -*- coding: utf-8 -*-
"""module_1_exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2JOW1BzwUEMwsuyZf_kzyAmbK9Oat2x

<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Python: Variáveis & Tipos de Dados
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---

# **Tópicos**

<ol type="1">
  <li>Introdução ao Google Colab;</li>
  <li>Variáveis;</li>
  <li>Números;</li>
  <li><i>Strings;</i></li>
  <li>Boleanos.</li>
</ol>

---

# **Exercícios**

## 1\. Google Colab

Crie uma célula de código que escreva o texto "Olá mundo!", utilize o comando `print`.
"""

print('Olá, mundo!')

"""Crie uma célua de texto e adicione uma imagem.

> Bloco com recuo

---

## 2\. Números

Preencha as células de código para preencher os valores de (A), (B) e (C) na tabela de ticket médio abaixo:

<br>

| Dia   | Valor Total Vendas | Qtd Total Vendas | Ticket Medio |
|-------|--------------------|------------------|--------------|
| 19/01 | (A)                | 3                | 320.52       |
| 20/01 | 834.47             | (B)              | 119.21       |
| 23/01 | 15378.12           | 5                | (C)          |
"""

# (A)951,56

# (B)7

# (C)3.075,62

"""---

## 3\. Strings

Aplique três métodos distintos na *string* abaixo, você pode conferir alguns métodos neste [link](https://www.w3schools.com/python/python_ref_string.asp):
"""

cancao = 'Roda mundo, roda gigante, roda moinho, roda pião.'

print(cancao.upper())

print(cancao.title())

print(cancao.find('gigante'))


print(cancao.replace('mundo', 'world'))

"""Extraia da string abaixo o valor da taxa **selic** na variável `selic` e o valor do **ano** na variavel `ano`. Imprima os valores na tela."""

noticia = 'Selic vai a 2,75% e supera expectativas; é a primeira alta em 6 anos.'

selic = noticia[12:17]
print(selic)
ano = noticia[62:69]
print(ano)

"""---

## 4\. Booleanos

Utilize a tabela da verdade para responder: qual o valor da variável x?
"""

a = False
b = True

x = not a & b
print(x)
# True
